### ISSUE TITLE
弱问下这种无监督训练向量表示 一般最少要多少数据呢？

### ISSUE THREAD

**Issue by guotong1988** [yym6472/ConSERT#13]
多谢多谢多谢
@yym6472

**Comment by yym6472** [comment]
训练数据肯定是越多越好。最少的话，按照我们在英文STS的少样本实验来看，1000+条无监督文本就能有较大的提升了（相比于BERT直接导出的句子表示）。所以我觉得至少1000条左右吧，而且数据分布最好和要应用的下游任务的数据分布一致（比如说下游任务是医学领域，那么训练的无监督文本最好也来自于医学领域）。
