### ISSUE TITLE
本项目的系统适配问题

### ISSUE THREAD

**Issue by C-SunRay** [yym6472/ConSERT#21]
看到了linux的scripts脚本，想问一下项目的系统问题在windows上也能跑吗？还是需要一些小修改呢？ 谢谢！

**Comment by yym6472** [comment]
应该可以的，我在windows上成功跑通过（不过用的CPU，仅用来调试代码有无问题），你可以试下，有问题的话再看看。

**Comment by C-SunRay** [comment]
了解 非常感谢 我会进行尝试
